### ISSUE TITLE
Getting stuck in the woods

### ISSUE THREAD

**Issue by Corax42** [tung/corics-quest#1]
I ran into one small bug in Coric's Quest. In the realm to the North, it is possible to walk off of bridges and walk around on the black tiles (not quite sure what they are - abyss? tarpit? shadow? creeping darkness?). That may well be on purpose, and it is generally harmless. There is one specific location though (see attached screenshots) where this allows you to leave the current game area at its southern edge, which will result in Coric being stuck on a wood tile in the next area, unable to move in any direction.

Thanks for the lovely game, I enjoyed playing it!
![coricsquest1](https://github.com/user-attachments/assets/b2998e54-cfd2-4085-b190-aa6d43a53e63)
![coricsquest2](https://github.com/user-attachments/assets/0946c77c-28aa-4ad1-8a09-a645b0981eb9)

**Comment by tung** [comment]
LOL that's definitely not supposed to happen.  Guess that's what happens when you blast out 20+ maps in two weeks.

I'm tempted to keep it because it's funny, but I don't want people to lose progress screwing around and getting stuck, so I should probably fix it.

Thanks for the kind words!

**Comment by Corax42** [comment]
It is a bit of a gamer trap! Once I figured out that you *can* walk on Darkness, I felt compelled to fully explore it - I half expected it to lead to a hidden chest somewhere :)
